### ISSUE TITLE
Does spacy textblob support all the languages avaliable in spacy? Or is it restricted to textblob languages?

### ISSUE THREAD

**Issue by rafaeloliveirabd** [SamEdwardes/spacytextblob#21]
I'd like to do some zero-shot classification and for that, I'm loading a specific spacy language and then use the doc._.blob.polarity to get the polarity back. I've been using for several languages, but I'd like to know if this is doable? Can we do, for example spacy.load("sv_core_news_lg") , adding the pipe and then getting the polarity results? Are we restricted to the TextBlob available languages?

Example:

```
if language_chosen == 'en':
        nlp = spacy.load('{}_core_web_lg'.format(language_chosen))
        nlp.add_pipe('spacytextblob')
    else:
        nlp = spacy.load('{}_core_news_lg'.format(language_chosen))
        nlp.add_pipe('spacytextblob')

    list_predictions = []
    dataframe = inp_file()
    print(dataframe.columns)
    cleanedCol = input("From which of the following columns should be selected? ")
    for index in tqdm(range(0,len(dataframe.index))):
        text = dataframe.loc[index, cleanedCol]
        doc = nlp(text)
        polarity = doc._.blob.polarity
        if polarity >= 0.3:
            list_predictions.append("positive")
        elif polarity < -0.3:
            list_predictions.append("negative")
        else:
            list_predictions.append("neutral")

```

Thank you

**Comment by SamEdwardes** [comment]
Thank you for the question. The answer is that yes you are restricted to TextBlob available languages. This is because spacytextblob is using the TextBlob API under the hood to get the sentiment score.

Check out the docs to see how to use with another language: https://spacytextblob.netlify.app/tutorial/textblob_extensions/#extensions

For example here is how you would use it with French (<https://github.com/sloria/textblob-fr>):

```python
import spacy
from spacytextblob.spacytextblob import SpacyTextBlob
from textblob import Blobber
from textblob_fr import PatternTagger, PatternAnalyzer

@spacy.registry.misc("spacytextblob.fr_blob")
def create_fr_blob():
    tb = Blobber(pos_tagger=PatternTagger(), analyzer=PatternAnalyzer())
    return tb

config = {
    "blob_only": True,
    "custom_blob": {"@misc": "spacytextblob.fr_blob"}
}

nlp_fr = spacy.load("fr_core_news_sm")
nlp_fr.add_pipe("spacytextblob", config=config)
text = u"Quelle belle matinée"
doc = nlp_fr(text)

print(doc)
# Quelle belle matinée
print(doc._.blob)
# Quelle belle matinée
print(doc._.blob.sentiment)
# Quelle belle matinée
```

If you want to add support for additional languages you would need to create a new TextBlob extensions: <https://textblob.readthedocs.io/en/dev/extensions.html>
